#!/usr/bin/env python

import sys

from rqt_gui.main import Main

plugin = 'segbot_concert_services.plugins.MultiRobotPatrollerPlugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
