#!/usr/bin/env python
#
# Based on the turtle_pond script from the concert_services_turtlesim package,
# originally authored by Daniel Stonier (d.stonier@gmail.com) and Jihoon
# Lee(jihoonlee.in@gmail.com).
#
# Original License: BSD
#   https://raw.github.com/robotics-in-concert/concert_services/license/LICENSE
#
##############################################################################
# About
##############################################################################

# Simple script to request a pre-configured number of strolling segbots.

##############################################################################
# Imports
##############################################################################

import rospy
import rocon_python_comms
import concert_service_utilities
import concert_scheduler_requests
import unique_id
import scheduler_msgs.msg as scheduler_msgs
import concert_msgs.msg as concert_msgs
from segbot_navigation_concert.msg import AvailableRobotArray
import rocon_uri

##############################################################################
# Classes
##############################################################################


class MultiRobotNavigation:
    '''
      Requets handling for getting its mittens on some segbot_stroll'ing
      segbots.
    '''
    __slots__ = [
        'service_name',
        'service_description',
        'service_priority',
        'service_id',
        'requester',
        'pending_requests',   # [uuid.UUID] list of request id's pending feedback from the scheduler
        'allocated_requests',  # [uuid.UUID] moved here from pending requests once granted
        'allocated_resources',
        'status_publisher'
    ]

    def __init__(self):
        ####################
        # Discovery
        ####################
        (self.service_name, self.service_description, self.service_priority, self.service_id) = concert_service_utilities.get_service_info()

        ####################
        # Setup
        ####################
        self.requester = self.setup_requester(self.service_id)
        self.pending_requests = []
        self.allocated_requests = []
        self.allocated_resources = []
        self.status_publisher = rospy.Publisher('available_robots', AvailableRobotArray, latch=True)
        number_of_segbots = rospy.get_param("robots", default=10)
        rospy.loginfo("MultiRobotNavigation : requesting %s segbots" % number_of_segbots)
        for unused_i in range(0, number_of_segbots):
            self.request_segbot()

    def setup_requester(self, uuid):
        try:
            scheduler_requests_topic_name = concert_service_utilities.find_scheduler_requests_topic()
        except rocon_python_comms.NotFoundException as e:
            rospy.logerr("MultiRobotNavigation : %s" % (str(e)))
            return  # raise an exception here?
        frequency = concert_scheduler_requests.common.HEARTBEAT_HZ
        return concert_scheduler_requests.Requester(self.requester_feedback, uuid, 0, scheduler_requests_topic_name, frequency)

    def request_segbot(self):
        '''
         Request a segbot.
        '''
        resource = scheduler_msgs.Resource()
        resource.id = unique_id.toMsg(unique_id.fromRandom())
        resource.rapp = 'segbot_rapps/simulated_segbot_nav_3ne'
        resource.uri = 'rocon:/'
        resource_request_id = self.requester.new_request([resource], priority=self.service_priority)
        self.pending_requests.append(resource_request_id)
        self.requester.send_requests()

    def requester_feedback(self, request_set):
        '''
          Keep an eye on our pending requests and see if they get allocated here.
          Once they do, kick them out of the pending requests list so _ros_capture_teleop_callback
          can process and reply to the interaction.

          @param request_set : the modified requests
          @type dic { uuid.UUID : scheduler_msgs.ResourceRequest }
        '''
        cancelled_requests = 0
        for request_id, request in request_set.requests.iteritems():
            if request_id in self.pending_requests:
                if request.msg.status == scheduler_msgs.Request.GRANTED:
                    self.pending_requests.remove(request_id)
                    self.allocated_requests.append(request_id)
                    # TODO doesn't handle the case when an allocated resource gets preempted.
                    self.allocated_resources.append(str(request.msg.resources[0].uri))
                    self.status_publisher.publish(self.allocated_resources)
            elif request.msg.status == scheduler_msgs.Request.GRANTED:
                completely_unallocated = True
                for resource in request.msg.resources:
                    if rocon_uri.parse(resource.uri).name.string != concert_msgs.Strings.SCHEDULER_UNALLOCATED_RESOURCE:
                        completely_unallocated = False
                if completely_unallocated:
                    cancelled_requests += 1
                    request.cancel()
            # Need to add logic here for when the request gets released
        for unused_i in range(0, cancelled_requests):
            self.request_segbot()

    def cancel_all_requests(self):
        '''
          Exactly as it says! Used typically when shutting down or when
          it's lost more allocated resources than the minimum required (in which case it
          cancels everything and starts reissuing new requests).
        '''
        self.requester.cancel_all()
        self.requester.send_requests()

##############################################################################
# Launch point
##############################################################################

if __name__ == '__main__':

    rospy.init_node('multi_robot_navigation')
    multi_robot_navigation = MultiRobotNavigation()
    rospy.spin()
    if not rospy.is_shutdown():
        multi_robot_navigation.cancel_all_requests()
